# Generated by Django 4.2.6 on 2023-11-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='account',
        ),
    ]
