# Generated by Django 4.2.6 on 2023-11-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_rename_students_course_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='account',
            new_name='students',
        ),
    ]
