# Generated by Django 4.2.6 on 2023-11-04 05:59

import courses.service.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video_text_image_file_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=courses.service.fields.OrderField(blank=True, default=0, verbose_name='Порядковый номер контента в модуле'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=courses.service.fields.OrderField(blank=True, default=0, verbose_name='Порядковый номер модуля в курсе'),
            preserve_default=False,
        ),
    ]
